[build]
command = 'hugo'
publish = 'public'

[build.environment]
HUGO_VERSION = '0.104.2'

[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'


# Redirect ONLY for the netlify.app host → primary .work domain
[[redirects]]
  from = "/*"
  to = "https://rongxin.work/:splat"
  status = 301
  force = true
  conditions = { Host = ["rongxinxu.netlify.app"] }